import { test, expect } from "../../fixtures/extension.fixture";
import { seedStorage, clearStorage, getStorage } from "../../fixtures/storage.fixture";
import { createSessionData, resetCounters } from "../../fixtures/data.fixture";
import { SidebarPage, ModalHelper } from "../../helpers/sidebar";
import { Selectors } from "../../helpers/selectors";

test.describe("Session CRUD operations", () => {
  test.beforeEach(async ({ sidebarPage }) => {
    resetCounters();
    await clearStorage(sidebarPage);
  });

  test("should display empty state when no sessions exist", async ({ sidebarPage }) => {
    const sidebar = new SidebarPage(sidebarPage);
    await sidebar.sessions.waitForView();

    const sessionCount = await sidebar.sessions.getSessionCount();
    expect(sessionCount).toBe(0);

    // New session button should be visible
    const newSessionButton = sidebarPage.locator(Selectors.sessions.newSessionButton);
    await expect(newSessionButton).toBeVisible();
  });

  test("should create a new session", async ({ sidebarPage }) => {
    const sidebar = new SidebarPage(sidebarPage);
    const modal = new ModalHelper(sidebarPage);

    await sidebar.sessions.waitForView();
    await sidebar.sessions.clickNewSession();

    await modal.waitForModal();

    // Fill in session name using the specific ID
    await sidebarPage.locator("#session-name").fill("My Test Session");

    // Save the session
    await modal.save();

    // Verify session was created
    await sidebarPage.waitForTimeout(500);
    const sessionNames = await sidebar.sessions.getSessionNames();
    expect(sessionNames).toContain("My Test Session");

    // Verify storage was updated
    const storage = await getStorage(sidebarPage);
    expect(storage.sessions).toHaveLength(1);
    expect(storage.sessions[0].name).toBe("My Test Session");
  });

  test("should display seeded sessions", async ({ sidebarPage }) => {
    const session1 = createSessionData({ name: "Session Alpha" });
    const session2 = createSessionData({ name: "Session Beta" });

    await seedStorage(sidebarPage, {
      sessions: [session1, session2],
      currentSession: null,
    });

    const sidebar = new SidebarPage(sidebarPage);
    await sidebar.sessions.waitForView();

    const sessionNames = await sidebar.sessions.getSessionNames();
    expect(sessionNames).toContain("Session Alpha");
    expect(sessionNames).toContain("Session Beta");
    expect(await sidebar.sessions.getSessionCount()).toBe(2);
  });

  test("should navigate to session products when clicking a session", async ({ sidebarPage }) => {
    const session = createSessionData({ name: "Clickable Session" });

    await seedStorage(sidebarPage, {
      sessions: [session],
      currentSession: null,
    });

    const sidebar = new SidebarPage(sidebarPage);
    await sidebar.sessions.waitForView();

    // Use name-based selection since IDs are generated by background script
    await sidebar.sessions.clickSessionByName("Clickable Session");

    // Should now be on products view
    await sidebar.products.waitForView();
    const title = sidebarPage.locator(Selectors.products.title);
    await expect(title).toContainText("Clickable Session");
  });

  test("should edit session name", async ({ sidebarPage }) => {
    const session = createSessionData({ name: "Original Name" });

    await seedStorage(sidebarPage, {
      sessions: [session],
      currentSession: null,
    });

    const sidebar = new SidebarPage(sidebarPage);
    const modal = new ModalHelper(sidebarPage);

    await sidebar.sessions.waitForView();
    await sidebar.sessions.editSessionByName("Original Name");

    await modal.waitForModal();

    // Clear and fill new name (edit mode uses 'edit-session-name')
    const nameInput = sidebarPage.locator("#edit-session-name");
    await nameInput.clear();
    await nameInput.fill("Updated Name");

    await modal.save();

    // Verify name was updated
    await sidebarPage.waitForTimeout(500);
    const sessionNames = await sidebar.sessions.getSessionNames();
    expect(sessionNames).toContain("Updated Name");
    expect(sessionNames).not.toContain("Original Name");

    // Verify storage was updated
    const storage = await getStorage(sidebarPage);
    expect(storage.sessions[0].name).toBe("Updated Name");
  });

  test("should delete session", async ({ sidebarPage }) => {
    const session = createSessionData({ name: "Session to Delete" });

    await seedStorage(sidebarPage, {
      sessions: [session],
      currentSession: null,
    });

    const sidebar = new SidebarPage(sidebarPage);
    const modal = new ModalHelper(sidebarPage);

    await sidebar.sessions.waitForView();
    expect(await sidebar.sessions.getSessionCount()).toBe(1);

    await sidebar.sessions.deleteSessionByName("Session to Delete");

    // Confirm deletion in modal
    await modal.waitForModal();
    await modal.confirmDelete();

    // Verify session was deleted
    await sidebarPage.waitForTimeout(500);
    expect(await sidebar.sessions.getSessionCount()).toBe(0);

    // Verify storage was updated
    const storage = await getStorage(sidebarPage);
    expect(storage.sessions).toHaveLength(0);
  });

  test("should handle multiple sessions", async ({ sidebarPage }) => {
    const sessions = [
      createSessionData({ name: "First Session" }),
      createSessionData({ name: "Second Session" }),
      createSessionData({ name: "Third Session" }),
    ];

    await seedStorage(sidebarPage, {
      sessions,
      currentSession: null,
    });

    const sidebar = new SidebarPage(sidebarPage);
    await sidebar.sessions.waitForView();

    expect(await sidebar.sessions.getSessionCount()).toBe(3);

    const sessionNames = await sidebar.sessions.getSessionNames();
    expect(sessionNames).toEqual(
      expect.arrayContaining(["First Session", "Second Session", "Third Session"])
    );
  });

  test("should preserve session settings after edit", async ({ sidebarPage }) => {
    // Create a session with specific settings
    const session = createSessionData({
      name: "Session to Rename",
      manageQuantity: true,
    });

    await seedStorage(sidebarPage, {
      sessions: [session],
      currentSession: null,
    });

    const sidebar = new SidebarPage(sidebarPage);
    const modal = new ModalHelper(sidebarPage);

    await sidebar.sessions.waitForView();
    await sidebar.sessions.editSessionByName("Session to Rename");

    await modal.waitForModal();

    // Edit only the name, keep other settings
    const nameInput = sidebarPage.locator("#edit-session-name");
    await nameInput.clear();
    await nameInput.fill("Renamed Session");

    await modal.save();

    // Verify session was renamed
    await sidebarPage.waitForTimeout(500);
    const sessionNames = await sidebar.sessions.getSessionNames();
    expect(sessionNames).toContain("Renamed Session");
    expect(sessionNames).not.toContain("Session to Rename");

    // Session should still be navigable
    await sidebar.sessions.clickSessionByName("Renamed Session");
    await sidebar.products.waitForView();
  });
});
