const CURRENCIES = [
  { code: "ALL", label: "Albania Lek", symbol: "Lek" },
  { code: "AFN", label: "Afghanistan Afghani", symbol: "؋" },
  { code: "ARS", label: "Argentina Peso", symbol: "$" },
  { code: "AWG", label: "Aruba Guilder", symbol: "ƒ" },
  { code: "AUD", label: "Australia Dollar", symbol: "$" },
  { code: "AZN", label: "Azerbaijan Manat", symbol: "₼" },
  { code: "BSD", label: "Bahamas Dollar", symbol: "$" },
  { code: "BBD", label: "Barbados Dollar", symbol: "$" },
  { code: "BYN", label: "Belarus Ruble", symbol: "Br" },
  { code: "BZD", label: "Belize Dollar", symbol: "BZ$" },
  { code: "BMD", label: "Bermuda Dollar", symbol: "$" },
  { code: "BOB", label: "Bolivia Bolíviano", symbol: "$b" },
  { code: "BAM", label: "Bosnia and Herzegovina Mark", symbol: "KM" },
  { code: "BWP", label: "Botswana Pula", symbol: "P" },
  { code: "BGN", label: "Bulgaria Lev", symbol: "лв" },
  { code: "BRL", label: "Brazil Real", symbol: "R$" },
  { code: "BND", label: "Brunei Dollar", symbol: "$" },
  { code: "KHR", label: "Cambodia Riel", symbol: "៛" },
  { code: "CAD", label: "Canada Dollar", symbol: "$" },
  { code: "KYD", label: "Cayman Islands Dollar", symbol: "$" },
  { code: "CLP", label: "Chile Peso", symbol: "$" },
  { code: "CNY", label: "China Yuan Renminbi", symbol: "¥" },
  { code: "COP", label: "Colombia Peso", symbol: "$" },
  { code: "CRC", label: "Costa Rica Colon", symbol: "₡" },
  { code: "HRK", label: "Croatia Kuna", symbol: "kn" },
  { code: "CUP", label: "Cuba Peso", symbol: "₱" },
  { code: "CZK", label: "Czech Republic Koruna", symbol: "Kč" },
  { code: "DKK", label: "Denmark Krone", symbol: "kr" },
  { code: "DOP", label: "Dominican Republic Peso", symbol: "RD$" },
  { code: "XCD", label: "East Caribbean Dollar", symbol: "$" },
  { code: "EGP", label: "Egypt Pound", symbol: "£" },
  { code: "EUR", label: "Euro", symbol: "€" },
  { code: "FKP", label: "Falkland Islands Pound", symbol: "£" },
  { code: "FJD", label: "Fiji Dollar", symbol: "$" },
  { code: "GHS", label: "Ghana Cedi", symbol: "¢" },
  { code: "GIP", label: "Gibraltar Pound", symbol: "£" },
  { code: "GTQ", label: "Guatemala Quetzal", symbol: "Q" },
  { code: "GGP", label: "Guernsey Pound", symbol: "£" },
  { code: "GYD", label: "Guyana Dollar", symbol: "$" },
  { code: "HNL", label: "Honduras Lempira", symbol: "L" },
  { code: "HKD", label: "Hong Kong Dollar", symbol: "$" },
  { code: "HUF", label: "Hungary Forint", symbol: "Ft" },
  { code: "ISK", label: "Iceland Krona", symbol: "kr" },
  { code: "INR", label: "India Rupee", symbol: "₹" },
  { code: "IDR", label: "Indonesia Rupiah", symbol: "Rp" },
  { code: "IRR", label: "Iran Rial", symbol: "﷼" },
  { code: "IMP", label: "Isle of Man Pound", symbol: "£" },
  { code: "ILS", label: "Israel Shekel", symbol: "₪" },
  { code: "JMD", label: "Jamaica Dollar", symbol: "J$" },
  { code: "JPY", label: "Japan Yen", symbol: "¥" },
  { code: "JEP", label: "Jersey Pound", symbol: "£" },
  { code: "KZT", label: "Kazakhstan Tenge", symbol: "лв" },
  { code: "KPW", label: "Korea (North) Won", symbol: "₩" },
  { code: "KRW", label: "Korea (South) Won", symbol: "₩" },
  { code: "KGS", label: "Kyrgyzstan Som", symbol: "лв" },
  { code: "LAK", label: "Laos Kip", symbol: "₭" },
  { code: "LBP", label: "Lebanon Pound", symbol: "£" },
  { code: "LRD", label: "Liberia Dollar", symbol: "$" },
  { code: "MKD", label: "Macedonia Denar", symbol: "ден" },
  { code: "MYR", label: "Malaysia Ringgit", symbol: "RM" },
  { code: "MUR", label: "Mauritius Rupee", symbol: "₨" },
  { code: "MXN", label: "Mexico Peso", symbol: "$" },
  { code: "MNT", label: "Mongolia Tughrik", symbol: "₮" },
  { code: "MZN", label: "Mozambique Metical", symbol: "MT" },
  { code: "NAD", label: "Namibia Dollar", symbol: "$" },
  { code: "NPR", label: "Nepal Rupee", symbol: "₨" },
  { code: "ANG", label: "Netherlands Antilles Guilder", symbol: "ƒ" },
  { code: "NZD", label: "New Zealand Dollar", symbol: "$" },
  { code: "NIO", label: "Nicaragua Cordoba", symbol: "C$" },
  { code: "NGN", label: "Nigeria Naira", symbol: "₦" },
  { code: "NOK", label: "Norway Krone", symbol: "kr" },
  { code: "OMR", label: "Oman Rial", symbol: "﷼" },
  { code: "PKR", label: "Pakistan Rupee", symbol: "₨" },
  { code: "PAB", label: "Panama Balboa", symbol: "B/." },
  { code: "PYG", label: "Paraguay Guarani", symbol: "Gs" },
  { code: "PEN", label: "Peru Sol", symbol: "S/." },
  { code: "PHP", label: "Philippines Peso", symbol: "₱" },
  { code: "PLN", label: "Poland Zloty", symbol: "zł" },
  { code: "QAR", label: "Qatar Riyal", symbol: "﷼" },
  { code: "RON", label: "Romania Leu", symbol: "lei" },
  { code: "RUB", label: "Russia Ruble", symbol: "₽" },
  { code: "SHP", label: "Saint Helena Pound", symbol: "£" },
  { code: "SAR", label: "Saudi Arabia Riyal", symbol: "﷼" },
  { code: "RSD", label: "Serbia Dinar", symbol: "Дин." },
  { code: "SCR", label: "Seychelles Rupee", symbol: "₨" },
  { code: "SGD", label: "Singapore Dollar", symbol: "$" },
  { code: "SBD", label: "Solomon Islands Dollar", symbol: "$" },
  { code: "SOS", label: "Somalia Shilling", symbol: "S" },
  { code: "ZAR", label: "South Africa Rand", symbol: "R" },
  { code: "LKR", label: "Sri Lanka Rupee", symbol: "₨" },
  { code: "SEK", label: "Sweden Krona", symbol: "kr" },
  { code: "CHF", label: "Switzerland Franc", symbol: "CHF" },
  { code: "SRD", label: "Suriname Dollar", symbol: "$" },
  { code: "SYP", label: "Syria Pound", symbol: "£" },
  { code: "TWD", label: "Taiwan New Dollar", symbol: "NT$" },
  { code: "THB", label: "Thailand Baht", symbol: "฿" },
  { code: "TTD", label: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { code: "TRY", label: "Turkey Lira", symbol: "₺" },
  { code: "TVD", label: "Tuvalu Dollar", symbol: "$" },
  { code: "UAH", label: "Ukraine Hryvnia", symbol: "₴" },
  { code: "GBP", label: "United Kingdom Pound", symbol: "£" },
  { code: "USD", label: "United States Dollar", symbol: "$" },
  { code: "UYU", label: "Uruguay Peso", symbol: "$U" },
  { code: "UZS", label: "Uzbekistan Som", symbol: "лв" },
  { code: "VEF", label: "Venezuela Bolívar", symbol: "Bs" },
  { code: "VND", label: "Viet Nam Dong", symbol: "₫" },
  { code: "YER", label: "Yemen Rial", symbol: "﷼" },
  { code: "ZWD", label: "Zimbabwe Dollar", symbol: "Z$" }
];

const DEFAULT_CURRENCY = "EUR";
